// @ts-check
/**
 * Prints the catalog of all Cucumber step definitions as Markdown, grouped by step definition file.
 * With `--write` it also saves the catalog to docs/steps-catalog.md.
 *
 *   npm run steps            # print
 *   npm run steps -- --write # print + update docs/steps-catalog.md
 *
 * Plain JavaScript on purpose: cucumber.yml already registers ts-node for the step definitions,
 * running this file through ts-node as well would compile them twice.
 */
const fs = require('node:fs');
const path = require('node:path');
const { loadConfiguration, loadSupport } = require('@cucumber/cucumber/api');

const CATALOG_PATH = path.join(__dirname, '..', 'docs', 'steps-catalog.md');

async function main() {
  const { runConfiguration } = await loadConfiguration();
  /** Runtime shape of the loaded library; the public `ISupportCodeLibrary` type does not expose it. */
  const support = /** @type {{ stepDefinitions: { keyword: string; pattern: string | RegExp; uri: string; line: number }[] }} */ (
    /** @type {unknown} */ (await loadSupport(runConfiguration))
  );

  /** @type {Map<string, { keyword: string; pattern: string; line: number }[]>} */
  const byFile = new Map();
  for (const def of support.stepDefinitions) {
    const file = path.relative(process.cwd(), def.uri);
    const rows = byFile.get(file) ?? [];
    rows.push({ keyword: def.keyword, pattern: String(def.pattern), line: def.line });
    byFile.set(file, rows);
  }

  const lines = [
    '# Cucumber step catalog',
    '',
    'Generated by `npm run steps -- --write`. Do not edit by hand.',
    'Reuse these steps when writing a scenario: `{string}` = text in double quotes, `{int}` = whole number.',
    '',
  ];
  for (const file of [...byFile.keys()].sort()) {
    lines.push(`## ${path.basename(file)}`, '', '| Keyword | Step | Line |', '|---------|------|------|');
    for (const row of byFile.get(file) ?? []) {
      lines.push(`| ${row.keyword} | \`${row.pattern.replace(/\|/g, '\\|')}\` | [${row.line}](../${file}#L${row.line}) |`);
    }
    lines.push('');
  }

  const markdown = lines.join('\n');
  process.stdout.write(markdown);
  if (process.argv.includes('--write')) {
    fs.writeFileSync(CATALOG_PATH, markdown);
    process.stderr.write(`\nWritten to ${path.relative(process.cwd(), CATALOG_PATH)}\n`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
